#!/bin/sh

echo "phase 0, saving optimized glibc"
( equery l sys-libs/glibc | head -1 > /tmp/sys-libs--glibc.version ) || exit
quickpkg --include-config y sys-libs/glibc || exit
glibc_ver='='`cat /tmp/sys-libs--glibc.version`

echo "phase 1, recompiling $glibc_ver"
export CFLAGS='-O2'
export CXXFLAGS="$CFLAGS"
emerge -q $glibc_ver || exit

echo "phase 2, compiling busybox"
export CFLAGS='-m32 -march=i386'
export CXXFLAGS="$CFLAGS"
export CHOST=i386-pc-bionic
export CC=`which gcc`
export CXX=`which g++`

INSTALL_ONLY='*/bin/busybox' \
 fat-gentoo-friendly_executable \
 /usr/portage/sys-apps/busybox/busybox-1.24.2.ebuild \
 android || exit

echo "phase 3, restoring $glibc_ver"
emerge -q --usepkgonly $glibc_ver || exit

echo 'success'
